### PR TITLE
feat:exposed visibility value for the provider in the DA

### PR DESCRIPTION
**Pull request by Aditya-ranjan-16**
### Description

exposed [visibility](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs#visibility) value for the provider in the DA , with default value set to "private"

[Git issue](https://github.ibm.com/GoldenEye/issues/issues/11322)
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

exposes visibility value for the provider in the DA

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
One more change required. Can you update the `cra-config.yaml` file and add the following TF_VAR:

`TF_VAR_provider_visibility: "public"`
(I'm surprised the pipeline passed without this change to be honest)

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@Aditya-ranjan-16 The test failed with this error:

`Error: [ERROR] Error when creating resource instance: Please contact the Service Provider for this error. [422, Unprocessable Entity] This account reached the number of Trial plan instances that are allowed. To proceed, you must select the Standard plan or delete an existing Trial instance. If you delete the Trial plan instance, you must also delete its reclamation by using the IBM Cloud CLI.`

However our test should not be creating a new secrets manager instance. I took a look, and it seems there is a bug in the complete example. To address, can you add a count around the secrets manager module call [here](https://github.com/terraform-ibm-modules/terraform-ibm-cloudant/blob/61bb635b630f975691066b8a43876d5f412d547e/examples/complete/main.tf#L80) like so:
`count                = var.existing_sm_instance_guid == null ? 1 : 0`

**Review by iamar7 — CHANGES_REQUESTED** [review]
@Aditya-ranjan-16 Can you please update 

`module.secrets_manager.secrets_manager_guid` -> `module.secrets_manager[0].secrets_manager_guid`

The complete example will fail if consumer wants to create a new sm_instance.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
